# ansible-based image
from willhallonline/ansible:2.18-alpine-3.18

# update and install necessary packages
run apk update && \
    apk add --no-cache \
    openssh-client \
    ca-certificates \
    bash \
    py3-netaddr
