# alpine-based image
from alpine:latest

# update and install necessary packages
run apk update && \
    apk add --no-cache \
    openssh-client \
    ca-certificates \
    bash \
    curl \
    jq \
    kubectl \
    helm
